### ISSUE TITLE
Linear Algebra

### ISSUE THREAD

**Issue by MarcusBryan1990** [MarcusBryan1990/ossu-data-science#1]
### Online Courses:
- [ ] Linear Algebra - Foundations to Frontiers (#2)
- [ ] Applications of Linear Algebra Part 1 (#3)
- [ ] Applications of Linear Algebra Part 2 (#4)

### YouTube Videos/Playlists:
- [ ] Khan Academy: Linear Algebra
- [ ] Mathematics for Machine Learning: Linear Algebra
- [ ] Essence of Linear Algebra #15

### Projects:
